apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - '../../../base'

patchesStrategicMerge:
  - delete-manifest.yaml

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: voting-alb

namespace: vote