apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - '../../../base'

patchesStrategicMerge:
  - delete-manifest.yaml

secretGenerator:
- name: vote-secrets
  files:
  - db_connection

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: voting-alb

namespace: vote