apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: vote-secrets
  namespace: vote
spec:
  name: vote-secrets3
  forceOverwriteReplicaSecret: true
  description: "Vote App Secrets"
  secretString:
    key: db_connection
    name: vote-secrets
    namespace: vote
---
apiVersion: v1
kind: Secret
metadata:
  name: vote-secrets
  namespace: vote
type: Opaque
stringData:
  db_connection: | 
    {
      "db_host": "10.0.144.23",
      "db_user": "postgres",
      "db_password": "postgres",
      "db_port": "5432",
      "redis_host": "10.0.144.23",
      "redis_port": "6379"
    }