apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: voting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting