apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: vote-secretsmanager
  namespace: vote
spec:
  name: vote-secrets5
  forceOverwriteReplicaSecret: true
  description: "Vote App Secrets"
  secretString:
    key: db_connection
    name: vote-secrets
    namespace: vote