apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack
  namespace: argocd
spec:
  destination:
    namespace: ack-system
    server: https://kubernetes.default.svc
  sources:
    - path: ''
      repoURL: oci://public.ecr.aws/aws-controllers-k8s/secretsmanager-chart
      targetRevision: 1.0.3
      # chart: secretsmanager-chart
      helm:
        values: |-
          aws:
            region: "ap-northeast-1'

          serviceAccount:
            create: false

  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
