apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting
  namespace: argocd
spec:
  destination:
    namespace: vote
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/dispiny/msa_voting_infra.git
      targetRevision: HEAD
      path: manifest/app/overlay/prod/worker/
      
    - repoURL: https://github.com/dispiny/msa_voting_infra.git
      targetRevision: HEAD
      path: manifest/app/overlay/prod/result/

    - repoURL: https://github.com/dispiny/msa_voting_infra.git
      targetRevision: HEAD
      path: manifest/app/overlay/prod/vote/

    - repoURL: https://github.com/dispiny/msa_voting_infra.git
      targetRevision: HEAD
      path: manifest/app/overlay/prod/infra/
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---

