apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - '../../../base'

patches:
  - path: service.yaml
    target:
      kind: Service
      name: service
  - path: ingress.yaml
    target:
      kind: Ingress
      name: voting-alb

replacements:
  - source:
      kind: Deployment
      name: deployment
    targets:
      - select:
          kind: Deployment
          name: deployment
        fieldPaths:
          - metadata.name
        options:
          create: true
namePrefix: vote-
namespace: vote