apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-alb
spec:
  rules:
    - host: result.jm.awssoft.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result-service
                port:
                  number: 80